### ISSUE TITLE
Allow all officers to see rsvp counts without being admins

### ISSUE THREAD

**Issue by alexander-zw** [compserv/hknweb#108]

**Comment by alexander-zw** [comment]
Also allow candidates to see number of rsvps

**Comment by jameslzhu** [comment]
Perhaps create two kinds of rsvp permissions, allowing officers to see full rsvp info while only allowing candidates to see the rsvp count?

Alternatively, we might show both candidates and officers the full rsvp info (counts and who is attending); it might encourage people to rsvp if they know who else is attending (similar to how Facebook encourages you to attend events friends are attending).

**Comment by alexander-zw** [comment]
According to act, allowing both to see the full info is fine. We should probably use user permissions.
