### ISSUE TITLE
Make links on candidate portal flexible

### ISSUE THREAD

**Issue by alexander-zw** [compserv/hknweb#135]
Create a model that admin can manage

**Comment by jameslzhu** [comment]
This ought to allow candidate portal links to adjust semester-to-semester:
- Not hard-coded into HTML
- Adjustable, any number (n) of links (adding new links later through the semester)
- Can be changed in admin interface through web model editing interface (/admin)
- Make links hide-able (add link at start of semester but hide until end)

**Comment by alexander-zw** [comment]
Check out the announcement model in candidate/models.py and admin.py
