### ISSUE TITLE
Make candidate requirements more flexible

### ISSUE THREAD

**Issue by alexander-zw** [compserv/hknweb#140]
Create a model that tracks requirements for initiation, so that special candidates can have different requirements tracked on the portal

**Comment by alexander-zw** [comment]
I feel like this would be very difficult. It's easy to have the number of required events for each type be user defined. But what if you need the sum of two event types to be some number? How do you deal with bit-byte and officer challenges? I feel like this might not be worth the hassle

**Comment by ochan1** [comment]
https://github.com/compserv/hknweb/pull/283

**Comment by bri25yu** [comment]
Closing since fixed by the PRs above
