### ISSUE TITLE
Make salary optional field for alumni form

### ISSUE THREAD

**Issue by jameslzhu** [compserv/hknweb#148]
Alumni shouldn't be discouraged to filling out our alumni form just because they don't want to disclose their salary. Even if we allow them the option to put in their salary (useful for prodev), we don't want to force it. (I believe Jaymo brought this up a few semesters ago.)

At a technical level, we should keep the field but allow it to be blank / null (for value / validation); using 0 as a default value might make it harder for filtering out salaries that are not set.

At a UI level, the form should have an explicit "Salary (optional)" label.

**Comment by alexander-zw** [comment]
Required parts already have a red asterisk, I don't think we need to explicitly say it's optional, though we could for emphasis?

**Comment by bri25yu** [comment]
Closed by https://github.com/compserv/hknweb/pull/404
