### ISSUE TITLE
dont hid events on calendar

### ISSUE THREAD

**Issue by dannychuy** [compserv/hknweb#150]
+ events hid the events. its not great :/

**Comment by alexander-zw** [comment]
When many events are on the same day the later ones are hidden and can only be seen when you click on see more. This is bad when the more important event such as GM is hidden. Not sure what the best way to fix this is

**Comment by dinganthony** [comment]
Is there a way to add functionality for "pinned" or "important" events without sacrificing ordering by event time?

**Comment by jameslzhu** [comment]
We can specify event ordering in FullCalendar: https://fullcalendar.io/docs/eventOrder

**Comment by dannychuy** [comment]
I would like to bump this. TBH I would prefer that none of the events are hidden since they are all 20/10 events :')

Of course this semester is an oddball since there are more than normal amount of events

**Comment by bri25yu** [comment]
Closed by https://github.com/compserv/hknweb/pull/404
