### ISSUE TITLE
Let VP have a holistic view of all the candidates and how much they have done.

### ISSUE THREAD

**Issue by dannychuy** [compserv/hknweb#165]
This means rows with candidate and columns of requirements

**Comment by dinganthony** [comment]
@alexander-zw @chevin-ken thoughts? how should we implement this

**Comment by chevin-ken** [comment]
@dinganthony this would be a table view exactly as danny described, with checkmarks at each spot in a grid indicating that the candidate along the row has completed the requirement at the column

**Comment by dinganthony** [comment]
@chevin-ken yeah I know, but right now RSVP objects have users as fields and not the other way around. I think what I'm asking is should we elect to make things easier for this task by rebuilding our models such that users have a field with all their RSVPs?

**Comment by dannychuy** [comment]
Wait, random note, can you make it a number? since some requirements are like go to 3 events. so knowing how many is good!

**Comment by alexander-zw** [comment]
I think putting this on the main site instead of admin is better, we can customize it more easily. Or maybe put it on admin but as a completely new page. No need to modify the model fields.

**Comment by jack-y-wang** [comment]
imo this is one of the main pros of us still using spreadsheets to track attendance v nice to use it to see how all candidates are doing throughout the semester and end of semester check-ins

**Comment by bri25yu** [comment]
Closed by https://github.com/compserv/hknweb/pull/395
