### ISSUE TITLE
Tying the user account to a google calendar and sharing it with the berkeley.edu mail

### ISSUE THREAD

**Issue by dannychuy** [compserv/hknweb#167]
I know you can click a link to add an event to the calendar. Put is there a way to subscribe to a "Danny Chu's HKN Calendar" so every time you RSVP, it automatically gets added?

**Comment by dannychuy** [comment]
On the opposite route, I think it would be super cool to have all the Gcalendars linked to the website and be able to toggle (for any officer) to see the calendar events!

**Comment by bri25yu** [comment]
Resolved by https://github.com/compserv/hknweb/pull/390
