### ISSUE TITLE
Officer/Canidate Attendance

### ISSUE THREAD

**Issue by dannychuy** [compserv/hknweb#171]
Look at the tbp attendance sheet.

**Comment by alexander-zw** [comment]
I'm not in tbp

**Comment by bri25yu** [comment]
@dannychuy can you post an ss of what the TBP attendance sheet looks like lol

**Comment by bri25yu** [comment]
![image](https://user-images.githubusercontent.com/46059916/95708531-609fe100-0c11-11eb-9637-be4502c7329d.png)

**Comment by bri25yu** [comment]
See https://github.com/compserv/hknweb/issues/236 also
> Also, since everyone has to go, it would be great if VP could confirm by uploading a CSV, or something that takes less time.

**Comment by bri25yu** [comment]
Closed by https://github.com/compserv/hknweb/pull/418
