### ISSUE TITLE
for the new website is it possible to make it so that the [delete exam] button is not so easily accessible/next to the [pdf][solutions] buttons etc on exam archives for tutoring admin

### ISSUE THREAD

**Issue by gkimball1** [compserv/hknweb#183]
For the new website is it possible to make it so that the [delete exam] button is not so easily accessible/next to the [pdf][solutions] buttons etc on exam archives for tutoring admin? Not sure what has/hasn't been implemented yet on the new site but that would be nice!

Perhaps like right-click functionality, or click an exam(s) to highlight it and then have a "delete selected exam(s)" button down at the bottom?

**Comment by jameslzhu** [comment]
@gkimball1 you’re a wonderful person, but this issue title is atrocious. Could you title this a bit more concisely?

**Comment by bri25yu** [comment]
Closing since we aren't hosting an exams database atm
