### ISSUE TITLE
In the course map, how do you generate the data 'chartinfo'?

### ISSUE THREAD

**Issue by WadeWuu** [compserv/hknweb#202]
https://hkn.eecs.berkeley.edu/courseguides
In the course map, how do you generate the data 'chartinfo'?

**Comment by WadeWuu** [comment]
@jameslzhu @paulshaoyuqiao
Can you tell me how to do that?

**Comment by jameslzhu** [comment]
Hello @WadeWuu, I think (some) relevant info has been documented [here](https://github.com/compserv/hknweb/wiki/Course-Map) in the wiki.

As for how /coursesurveys/chartinfo is generated, I'm afraid it's not well-documented and you'll have to dig through some of the code in the hkn-rails repository [here](https://github.com/compserv/hkn-rails), which is the current production code running at hkn.eecs.berkeley.edu.

Following the routing information in [config/routes.rb](https://github.com/compserv/hkn-rails/blob/master/config/routes.rb), it appears the /courseguides/chartinfo points to the [courseguide_controller.rb](https://github.com/compserv/hkn-rails/blob/master/app/controllers/courseguide_controller.rb), specifically the `get_courses_json` method, which then calls `get_coursechart_json` in [course_chart_helper.rb](https://github.com/compserv/hkn-rails/blob/master/app/helpers/course_chart_helper.rb).

It appears all that happens is a Ruby Hash (dict, in Python) is assembled, containing information from all courses, and is then formatted into a string JSON before being returned.

If you are still curious about how the course data is represented in the database, that is another can of worms, but I can at least link you to the [Course](https://github.com/compserv/hkn-rails/blob/master/app/models/course.rb) ActiveRecord model.

As an aside, I'm not sure why you tagged @paulshaoyuqiao? Until recently this year he wasn't involved with development for HKN.

**Comment by jameslzhu** [comment]
If you're still unsure what's going on, feel free to re-open this issue. This is the best of my knowledge without explaining the Ruby code itself.
