### ISSUE TITLE
no such table: hknweb_announcement

### ISSUE THREAD

**Issue by WadeWuu** [compserv/hknweb#205]
I have successfully built the web by installing Vagrant and VirtualBox. However, after I make, the website show me that.
![image](https://user-images.githubusercontent.com/35893383/77711771-d8f3db80-700c-11ea-987a-6871590b063c.png)
I find I have unapplied migration(s). When I run 'python manage.py migrate' to apply them, it occurs that.
![image](https://user-images.githubusercontent.com/35893383/77712458-c9759200-700e-11ea-8b58-47d4a55dff34.png)

Sorry, I have solved it by pipenv run python manage.py migrate

**Comment by jameslzhu** [comment]
Hello @WadeWuu, are you sure this is the right website you’d like to run? If you’re looking to see how the course map works, from #202, it is implemented at https://github.com/compserv/hkn-rails, a separate repository.

**Comment by WadeWuu** [comment]
Thank you @jameslzhu . I am not sure is the right website you’d like to run. I am still looking to see how the course map works. I will see the hkn-rails. Thank you!!!

**Comment by WadeWuu** [comment]
Hi @jameslzhu , I have another question that in the admin page, does it support we generate the course map manually by typing the coures one by one?

**Comment by jameslzhu** [comment]
@WadeWuu I assume you are running the hknweb (Python) site. There is “addCourse” functionality but hknweb *does not yet implement the course map*. It is simply using the default Django admin interface for creating and editing model objects, documented at https://docs.djangoproject.com/en/3.0/ref/contrib/admin/, which simply creates objects and has no relation to the course map render. (It just runs SQL queries.)

I’d like to be clear: the course map implementation is in [hkn-rails](https://github.com/compserv/hkn-rails), which is the code actually running at hkn.eecs.berkeley.edu. This repo, hknweb, is a *beta* site, and has no relation to the site you see at hkn.eecs.berkeley.edu.

Also, the hkn-rails implementation does not have any UI for adding courses, either. I described how we added courses in the email I sent you, but currently it is a manual, command-line process for adding courses to the map.

From what you described, I think you are looking for a way to automatically create course map nodes for *many* courses at once. To some degree we do automatically generate nodes based on existing prerequisite data, but we have no such bulk upload feature. If you want such a feature I would recommend you implement one yourself by uploading a CSV text file and parsing the data yourself.

**Comment by jameslzhu** [comment]
I hope this has been helpful, but I would like to keep this repo’s Github issues focused for development for this site. Please email me if you still have questions, but I can’t guarantee we will have the code that does what you are looking for.
