### ISSUE TITLE
RSVP List Pagination

### ISSUE THREAD

**Issue by bri25yu** [compserv/hknweb#211]
It'd be pretty helpful to have pagination in the RSVP's list for events, especially for massive events like Big Funs, or GM's. This may also be an excuse to spruce up the events page html, such as adding a search function for rsvps after pagination has been implemented. 

![hknweb need rsvp list pagination](https://user-images.githubusercontent.com/46059916/79172345-4d6aa080-7da9-11ea-93df-262747ae96a1.PNG)

**Comment by dannychuy** [comment]
Also, can this page show which RSVPs were confirmed? Like make the name green or have a green check next to the name.

**Comment by bri25yu** [comment]
"Danny [Sp20 VP] mentioned also splitting them into officers, candidates, etc."
