### ISSUE TITLE
Showing RSVP confirmations on the calendar

### ISSUE THREAD

**Issue by dannychuy** [compserv/hknweb#212]
When I confirm RSVPs for events, since its through the django admin, its hard to view which events I've confirmed for already. It would be nice to see on the public view. One way would be the suggestion below.

Also, can this page show which RSVPs were confirmed? Like make the name green or have a green check next to the name. (written on #211 )

Another thing that would be nice would be to attend people on the site view (access given to execs or smth) instead of the django admin so I didn't have to look at that.

**Comment by alexander-zw** [comment]
It might be too hard to do this on the existing page, so I think creating a new page for this is the best way

**Comment by jameslzhu** [comment]
Not sure if we need an entirely new page for this; once upon a time I had an events listing at the bottom (for demo purposes), just an `ul` of events RSVP'd to. Idk about eventual design but either a sidebar or a listing under the calendar might be good enough, and here we might add the green RSVP confirmation check for candidates to see.
