### ISSUE TITLE
Course surveys functionality

### ISSUE THREAD

**Issue by bri25yu** [compserv/hknweb#233]
We need course survey functionality on the new website. Make sure to correspond with CSEC and the dept.

**Comment by jerrysong1324** [comment]
Estimated Deadline to upload Spring 20 data: beginning of Fall 20 semester
Estimated Deadline to upload Summer 20 data: week 3 of Fall 20 semester
Estimated Deadline to upload Fall 20 data: beginning of Spring 21 semester
Estimated Deadline to upload Spring 21 data: beginning of Fall 21 semester

I think this is pretty tough, so here are some potential deadlines for this project. 

Contact jerrysong@hkn.mu or csec@hkn.mu for any questions.

**Comment by dannychuy** [comment]
@jack-y-wang This is you.

**Comment by dannychuy** [comment]
Also, Low Pri. if we can have a print functionality for a standard report for GSIs to print their evals to PDF, that would be cool.
