### ISSUE TITLE
Confirming Candidate Event Attendance

### ISSUE THREAD

**Issue by jerrysong1324** [compserv/hknweb#235]
If candidate A goes to event X but was on the waitlist, the candidate doesn't seem to get confirmed for the event. Alternatively, if candidate B rsvp'd to event X but did not show up, that candidate still gets credit I think? 

This is pretty important if we wanna transition to candidate tracking purely through website. 
However, it's lower priority than course surveys imo : )

**Comment by dannychuy** [comment]
This already happens. Lowkey, the waitlist/not waitlist difference doesn't matter for event attendance.
