### ISSUE TITLE
Migrating the calendar as a google calendar - With a plugin to RSVP easily

### ISSUE THREAD

**Issue by dannychuy** [compserv/hknweb#250]
I'm imagining that the Calendar window, next to the Accept Decline, there is an RSVP button as well. To do this, it would be a google chrome plug in. Thought it may be a fun cand project.

**Comment by bri25yu** [comment]
Adding GCal resolved by https://github.com/compserv/hknweb/pull/390. Not sure about the RSVP button on the calendar itself
