### ISSUE TITLE
Autofill blocks Event Creation Date/Time Dropdown

### ISSUE THREAD

**Issue by amyhung99** [compserv/hknweb#258]
- The calendar/time dropdown to select the date + time for a new event is great, but the autofill field blocks the calendar unless you type something in to get rid of the suggestions
- please turn off autofilling in the field if possible :^)

![image](https://user-images.githubusercontent.com/17733033/95263347-7f9e0d80-07e2-11eb-99bc-4ce4550bacd9.png)
![image](https://user-images.githubusercontent.com/17733033/95263354-8462c180-07e2-11eb-95c0-423fff2d34dc.png)

**Comment by bri25yu** [comment]
Can't find the PR this was fixed, but it's fixed by https://github.com/compserv/hknweb/blob/8e2b97d856d06ccae4945b0fec785d938435ef6d/hknweb/events/utils.py#L53
