### ISSUE TITLE
RSVPing to a calendar event

### ISSUE THREAD

**Issue by amyhung99** [compserv/hknweb#261]
- v small complaint, but after RSVPing to a calendar event, it takes two back clicks to go back to the main calendar
- would also be nice to return to the same month in the calendar (e.g. if I'm looking through all the events and RSVP to an event in December, I'd like to be able to backtrack to the calendar + be on the month of December, not the current month)

**Comment by bri25yu** [comment]
I think the first may be solved by `https://dev-hkn.eecs.berkeley.edu/events/rsvps?option=semester`?

**Comment by bri25yu** [comment]
Closed by https://github.com/compserv/hknweb/pull/403
