### ISSUE TITLE
Mandatory meetings lists all previous mandatory meetings, not just from this semester

### ISSUE THREAD

**Issue by bri25yu** [compserv/hknweb#262]
![compserv candidate portal mandatory events from all previous semesters](https://user-images.githubusercontent.com/46059916/95281625-817cc680-080c-11eb-99d6-6234ce148e0b.PNG)

**Comment by jerrysong1324** [comment]
Can you change Officer Hangouts to 2 required as well? : )

**Comment by jerrysong1324** [comment]
oh oh, also the "pay all dues (2 sets)" can you make that just "pay dues" tytyty
