### ISSUE TITLE
Event time zone inconsistency

### ISSUE THREAD

**Issue by jameslzhu** [compserv/hknweb#263]
Reported by andrew_zhang on Slack:

> Just wanted to let you know that when you try to edit pre-existing events already on the hkn.mu/beta calendar, the time will erratically move some number of hours ahead on its own. I feel like it's a fixed amount and could be some issue with the time zone or something.  
To test, just add an event to the calendar, save it with some set time, and then try to edit it.

**Comment by ochan1** [comment]
This was on the HKN Rails website as well, but I was able to temporarily set it to PT for there (I know this is HKN Web, just saying a related experience)

Should we standardize in the Website settings to PT for the website?

**Comment by bri25yu** [comment]
Closed by https://github.com/compserv/hknweb/pull/269
