### ISSUE TITLE
Add rollbar error reporting

### ISSUE THREAD

**Issue by jameslzhu** [compserv/hknweb#34]
[Rollbar](https://rollbar.com/error-tracking/django/) is an online error reporting service. It aggregates errors by type and traceback (location) and emails us when they occur (at order-of-magnitude intervals: first time, 10th, 100th, 1000th, etc.). We use it with the rails site, as it’s easier than scrolling through the log files.

Integrating this with the Django website would be very helpful for tracking down errors on the live site, especially with bad urls.

The Python library for interfacing with rollbar is at https://github.com/rollbar/pyrollbar.

**Comment by bri25yu** [comment]
Closed due to https://github.com/compserv/hknweb/blob/a01ffd8587859bf63c46213be6a0c8b87164a5c2/hknweb/settings/common.py#L173
