### ISSUE TITLE
Better testing / Travis CI

### ISSUE THREAD

**Issue by jameslzhu** [compserv/hknweb#41]
Testing is pretty much non-existent right now.

The current [Travis-CI](https://travis-ci.org/compserv/hknweb), configured with [.travis.yml](https://github.com/compserv/hknweb/blob/master/.travis.yml), does three things on a freshly installed Ubuntu 16.04 OS:
- Install dependencies, with pipenv
- Run SQL migrations (`python manage.py migrate`)
- Run checks (`python manage.py check`)

And that's it. No tests on if anything *actually* works, no tests if urls hit the right pages, no checks if methods work, or really anything.

A good first start on this will be route tests: checking if a GET request to a specific url returns the right page. Beyond this we can check for db functionality on POST / GET requests, etc.

Relevant docs pages:
- [Django reference on testing](https://docs.djangoproject.com/en/2.1/topics/testing/overview/)
- [Django tutorial on testing](https://docs.djangoproject.com/en/2.1/intro/tutorial05/)
- [Testing tools](https://docs.djangoproject.com/en/2.1/topics/testing/tools/)

**Comment by bri25yu** [comment]
Closed by https://github.com/compserv/hknweb/pull/447 and https://github.com/compserv/hknweb/pull/443
