### ISSUE TITLE
Usertastrophe (or migrationcalypse?)

### ISSUE THREAD

**Issue by jameslzhu** [compserv/hknweb#46]
This could either not be a problem, or be a ticking time bomb that will only get worse with time.

Source: [Substituting a custom User model](https://docs.djangoproject.com/en/2.1/topics/auth/customizing/#substituting-a-custom-user-model)

> Changing AUTH_USER_MODEL after you’ve created database tables is significantly more difficult since it affects foreign keys and many-to-many relationships, for example.
> This change can’t be done automatically and requires manually fixing your schema, moving your data from the old user table, and possibly manually reapplying some migrations. See #25313 for an outline of the steps.
> Due to limitations of Django’s dynamic dependency feature for swappable models, the model referenced by AUTH_USER_MODEL must be created in the first migration of its app (usually called 0001_initial); otherwise, you’ll have dependency issues.

If we'd like to integrate Google OAuth login (aka OpenID Connect) in the future, this *might**** require customizing `User` with a custom subclass:

```py
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass
```

Unfortunately, since this has to be done as the very first app migration, this might require us to nuke the SQL migrations in every app tied to User and regenerate them from scratch.

***
There is hope on the horizon; glancing at Google Django integrations like [social-auth-app-django](https://github.com/python-social-auth/social-app-django), they appear to use completely separate auth models, and do not seem to require modifying AUTH_USER_MODEL.

This will require investigation into whether is is the time bomb I worry it is.

**Comment by bri25yu** [comment]
Not sure if this is relevant anymore since we have Profiles, so closing for now. If this issue pops up we'll just reference this issue
