### ISSUE TITLE
Provision Terence Neo Berkeley HKN accounts

### ISSUE THREAD

**Issue by bri25yu** [compserv/hknweb#486]
From: Terence Neo
Date: Thu, Sep 22, 2022 at 4:22 PM
Subject: Re: Getting involved with HKN
To: Jeffrey Deng

Hi Jeffrey,

Thanks for the reply.

Sure, you should be able to find my name (Neo Yu Yao Terence) on the chapter's website here: https://nushkn.org/members/

Best regards,
Terence

On Thu, Sep 22, 2022 at 10:31 AM Jeffrey Deng wrote:
Hi Terence,

I'm so sorry about the delay in communication! Could you please send me any proof of membership from your undergrad institution (doesn't have to be super formal just something that I can use to verify)? After that, I can add you to our Slack and help get you set up with creating accounts for our platforms. Please let me know if you have any questions!

Best,
Jeffrey

On Sat, Sep 17, 2022 at 12:42 PM Terence Neo wrote:
Hi Jeffery,

I am an EECS grad student with a lifetime HKN membership from my undergrad institution.
May I know how should I get involved with HKN at Cal?

Looking forward to hearing from you.

Best regards,
Terence

**Comment by ochan1** [comment]
Removed the emails to mitigate scraping

**Comment by ochan1** [comment]
Email sent, awaiting form fill out and email response

**Comment by ochan1** [comment]
Form filled by Terence and account created
