### ISSUE TITLE
Events calendar gcal integration

### ISSUE THREAD

**Issue by jameslzhu** [compserv/hknweb#55]
Figure out how to import / export from Google Calendar to the events calendar.

I have no idea how to do this: libraries, design, or Google APIs. Research required.

**Comment by dannychuy** [comment]
https://github.com/compserv/hknweb/blob/aff1b43034b84ca03481c34535bab98ea96ce321/hknweb/events/templates/events/show_details.html#L41

http://www.google.com/calendar/event?action=TEMPLATE&dates=20200419T100000Z%2F20200419T110000Z&text=%3Cevent.name%3E&location=%3Cevent.location%3E&details=%3Cevent.description%3E

**Comment by jameslzhu** [comment]
Hm, so it seems like the issue is that Python variables are not being evaluated in the template. Maybe wrapping them in {{ variable }} will do the trick.

**Comment by bri25yu** [comment]
From @dannychuy: 

> This is what I use to make clickable bCal events, thought it would be helpful to look at if you wanted to add that feature to the website. http://kalinka.tardate.com/ Google lets you template a url, so it shouldn't be too stressful

> Also, if anyone is in tbp IT, maybe y'all can look at their event -> bcal for inspiration. (ik its not a simple c&p)

**Comment by bri25yu** [comment]
Closed by https://github.com/compserv/hknweb/pull/390
