### ISSUE TITLE
Exams revamp

### ISSUE THREAD

**Issue by jameslzhu** [compserv/hknweb#56]
Exam archives were implemented in #14. I think the functionality works as-is, but there are some things which are still desired:

- Uploads are managed through the django admin interface. Requires admin logins (which we would like to restrict to compserv), and 
- We'd like to be able to indicate whether professors *refused* to release their exams for that semester. This is very beneficial to all parties: we visibly demonstrate that we respect professors' requests to avoid uploading their exams, and students will (hopefully) not hold the misconception that we are slacking on exam uploads. This also leaves a paper trail for future tutoring officers, who (in the absence of other records) can heuristically determine if professors do not want their exams released. (We may still want to ask every semester, however.) Alternatively, we may also want an internal-only indicator that professors have permanently opted out of releasing their exams.
- Departments are hard-coded. If we decide to support other "departments", especially "EECS", we should convert this to a ForeignKey.
- IDs are hard-coded as an IntegerField. We'd like to convert this to an implicit AutoField (to pseudo-guarantee uniqueness) by removing this field from the Course and CourseSemester models.
- Semesters are length-255 CharField fields. This may not be desirable. The current encoding scheme consists of naming semesters by "YYYYS", where YYYY is the year and S=1 in the spring, S=3 in the fall. (S=2 is ostensibly reserved for summer sessions.) We might want to encode semesters as models, or perform some sort of database validation to ensure consistency.
- Instructors are encoded as strings. We'd rather encode them as Instructor objects, which can be fixed for typos once (across the whole database), added independently, and verified with other validation checks. (This would also let us cross-link all exams from a single instructor easily.) This should be converted to a ForeignKey.
- Exam categories are hard-coded as Midterm 1, 2, 3, and Exam. This works well for the table format, but I'm unsure if this accommodates courses that use "quests" (quiz tests). (This might just be an optional thing.)
- Making exams harder to delete. (I haven't checked the implementation in hknweb right now, but in the hkn-rails site the button to delete is right next to the button to view, if you're logged in with permissions to delete.)

**Comment by bri25yu** [comment]
HKN is no longer holding an exams database
