### ISSUE TITLE
Course map revamp

### ISSUE THREAD

**Issue by jameslzhu** [compserv/hknweb#59]
Note: this is separate from #30, which deals with reducing the render time of the *existing* course map.

This is the master issue for the course map redesign. Next to exams and course surveys, the course map is probably the most visible and important part of the site for the department, professors, and students for long-term course planning and the evolution of EECS demographics and interests.

This is important. Thousands of students will plan and have planned their career at Berkeley based in part on this course map. This will affect course enrollments and departmental funding.

With that out of the way, let's dive in.

You should get access to the hkn-rails source repo at https://github.com/compserv/hkn-rails.

The front-end design of the course map is detailed at https://github.com/compserv/hknweb/wiki/Course-Map.

Internally, the course map is represented as a directed graph, with nodes representing courses and arrows representing prerequisites. It is stored as an adjacency graph, with nodes containing a list of prerequisites and arrows containing a parent / child node.

The most important changes which need to occur is:
1. **Merging the CS and EE graphs.**
Visually, they should remain discrete, but logically they should be rendered as a single graph.
We will need cross-departmental links between such pairings as CS189 and EE126/127, and potentially 

2. 
jasdkfjaklsdjfajskldf
i should finish writing this

**Comment by jameslzhu** [comment]
At the latest tutoring meeting, Sean presented his almost-complete design for the new course map, with feedback from several EECS professors.
Details are at https://github.com/compserv/hknweb/wiki/Course-Map-Design#minutes-tutoring-meeting-2018-10-26.

**Comment by bri25yu** [comment]
Closed by https://github.com/compserv/hknweb/pull/401
