### ISSUE TITLE
Officer challenge confirmation fixes

### ISSUE THREAD

**Issue by alexander-zw** [compserv/hknweb#61]
When someone requests an officer challenge, anyone can confirm/deny the challenge if given the link, not just the officer that gave the challenge. Need authentication.

If the challenge is already reviewed, should have some page that reminds officer it is already reviewed (are you sure you want to edit?). This is not super necessary though.

**Comment by jameslzhu** [comment]
I'd suggest that any officer be allowed to confirm the challenge, not necessarily just the person who did it.
Alternatively, give vp / csec / requesting officer the authorization to confirm the challenge.

Perhaps to model the three states of challenges (unreviewed, confirmed, denied), we can use an enum / integer field for this, with limited choices. We should definitely allow officers to change a deny to confirm, especially if they clicked the wrong thing.

**Comment by alexander-zw** [comment]
New issue: csec needs to confirm the officer challenge as well. Not sure what the best way to provide csec's email is: should we use csec@?

**Comment by alexander-zw** [comment]
Also add names to list of officers instead of just username

**Comment by alexander-zw** [comment]
Update: sending email to challenges@ is fine

**Comment by alexander-zw** [comment]
Actually, I'll just make it so that csec goes to the admin page to confirm challenges

**Comment by alexander-zw** [comment]
Merged
