### ISSUE TITLE
Officer portal for officer challenges

### ISSUE THREAD

**Issue by alexander-zw** [compserv/hknweb#62]
Make the portal where an officer can view all challenges requested from them, including ones reviewed and not reviewed

**Comment by jameslzhu** [comment]
Bump, this needs to be done within the next week or so.

**Comment by alexander-zw** [comment]
We currently have a page that does this, we just don't have a link to it

**Comment by bri25yu** [comment]
See https://dev-hkn.eecs.berkeley.edu/cand/offreq
