### ISSUE TITLE
Docker / container instead of Vagrant VM

### ISSUE THREAD

**Issue by jameslzhu** [compserv/hknweb#82]
Vagrant is rather heavyweight for a dev environment, if familiar. Could we get away with running Docker / containerd containers, and use that instead?

Metrics:
- User-friendliness: cannot be any harder for newcomers than Vagrant
- Download size: slower downloads = more time waiting to start developing
- Performance: same order-of-magnitude as VM (X% slower / faster is acceptable)
- Dev / prod similarity: must be able to run same MySQL / Python stack as prod

This would have the (theoretical) advantage of being able to plug into (potential) future containerized OCF infrastructure.

**Comment by bri25yu** [comment]
We'll probably stick with Vagrant for the near and far future lol. The one-time setup for Vagrant is relatively smooth imo and it's not that memory intensive
