### ISSUE TITLE
Write setup.sh for environment setup

### ISSUE THREAD

**Issue by jameslzhu** [compserv/hknweb#83]
Historically I’ve never liked setup.sh scripts, but we might as well use one:

- It’s already written in the Vagrantfile for provisioning
- We can point new developers to run setup.sh if they don’t want a VM
- We can solve this HKNWEB_MODE madness by setting it to dev in setup.sh, and just not using setup.sh in prod
- We can check that people are using the virtualenv with VIRTUAL_ENV
- Add pre-commit hooks for everyone

If we want to steal some code, CSM has a decent example which covers lots of edge cases:

https://github.com/csmberkeley/csm_web/blob/dev/setup.sh

**Comment by ochan1** [comment]
Each bullet response
* Yep
* The point of a VM is to have the same OS as the destination server, and we have a Makefile make command in https://github.com/compserv/hknweb/pull/431 to automatically install everything needed on the MacBook
* Makefile has the HKNWEB_MODE flag automatically set, people are encouraged to use Makefile equivalent to abstract this away (or remember HKNWEB_MODE must be set, which it does by erroring out)
* All Python Makefile commands uses the ".venv/bin/python" binary, encourage to use Makefile equivalent
* https://github.com/compserv/hknweb/pull/443 and https://github.com/compserv/hknweb/pull/447

Conclusion: Encourage use of Makefile commands to abstract away the commands and paths here
