### ISSUE TITLE
Add data migration for initial (seed) groups in database

### ISSUE THREAD

**Issue by jameslzhu** [compserv/hknweb#94]
https://docs.djangoproject.com/en/2.2/topics/migrations/#data-migrations

We'll need to add the following Groups for permissions to work:

- [ ] officer
- [ ] candidate

(not plural)

This is required for new development instances (i.e. new developers), who initialize new (blank) databases and thus will have any functionality involving candidates or officers broken until they manually add candidate and officer groups.

**Comment by bri25yu** [comment]
Closed by https://github.com/compserv/hknweb/pull/238
